lunar-linux/moonbase-kde

development/korundum/PRE_BUILD

When 0 it seems ruby doesn't set RUBY_VERSION_PATCH at all.

korundum: fix build with ruby 2.2.0

---

applications/kdegraphics-thumbnailers/BUILD
applications/kdegraphics-thumbnailers/DEPENDS
applications/libkexiv2/BUILD
applications/libkexiv2/DEPENDS

these were still listed as qt4

Kde qt5 dependencies

---

utils/phonon/PRE_BUILD

The problem came up because qt5 requires -fPIC but cmake assumes
PIE is enough (and damn, it should be).

phonon: fix build with qt5 & gcc 5

---

qt5/DETAILS
qt5/PRE_BUILD

Current qt5 doesn't build anymore because it is incompatible with the current
nss release.
Now qt5 HAS to be rebuilt as icu4c got bumped.
Please merge this soon.

qt5: bump to qt5.6 PLEASE MERGE

---

qt5-apps/qtwebkit/BUILD
qt5-apps/qtwebkit/PRE_BUILD

also moved all patching to PRE_BUILD,
where it belongs.

qtwebkit: fix build with an --as-needed system

---

qt4-apps/qt4/POST_INSTALL

pinentry now depends on qt5 and lin in POST_INSTALL is bad practice anyway.

qt4: don't rebuild pinentry in POST_INSTALL

---

qt5-apps/PyQt5/BUILD

These are required by calibre.

PyQt5: re-enable sip files

---

qt5-apps/PyQt5/DETAILS

The old version produces a segfault when trying to build our calibre module.

PyQt5: version bump

---

frameworks/extra-cmake-modules/DETAILS

The repo for version 5.31.0 no longer exists

extra-cmake-modules: version bump to 5.40.0

---

qt5-apps/PyQt5/BUILD

Things that build sip python bindings that depend on PyQt
will simply fail if these files are not there.
Installing PyQt5 without sips is
like installing libpyqt5 without libpyqt5-dev.
We are not Debian.

PyQt5: sips are required!

---

system/qt5/CONFIGURE

this will reduce both compilation time and space needed for a complete qt5 build
although someone may find the qtlocation build NOT really related with qtwebengine

qt5: if user select NOT to intsall qtwebengine then don't build qtlocation too

---

multimedia/qtwebengine/DETAILS

qtwebengine:Bump to 5.14.2
We should bump qtwebengine to qt5's VERSION when Qt5 bump to a new VERSION.

qtwebengine:Bump to 5.14.2

---

themes/qt5ct/BUILD
themes/qt5ct/DEPENDS
themes/qt5ct/DETAILS

qt5ct is a QT theme configuration utility that works without KDE / KF5 integration. Useful for GTK-based systems that also use QT apps.

qt5ct - theme configuration for non-KDE desktops

---

development/qt-creator/DEPENDS

openssh-askpass no longer exists in the moonbase
switching to ksshaskpass is a logical replacement.

qt-creator: DEPENDS update

---

office/scribus/patch.d/scribus-1.5.6-docdir.patch
office/scribus/patch.d/scribus-1.5.6.1-poppler-21.03.0-1.patch
office/scribus/patch.d/scribus-1.5.6.1-poppler-21.03.0-2.patch
office/scribus/patch.d/scribus-1.5.6.1-poppler-21.04.0.patch

Four patches lifted from gentoo:
- One patch (docdir.patch) that properly closes an if statement.
- Three patches to ensure poppler compatability - scribus breaks without it.

scribus - poppler patches

---

libs/PyQt5/DEPENDS

There's a circular dependency with PyQt5 and qscintilla2 - both of them list list the other as a dependency.
However, qscintilla2 is _not_ a requirement to compile PyQt5, so this is easily fixed by removing the _depends_

PyQt5 - circular dependency

---

libs/qca/DEPENDS

The existing configuration option for Botan (-DWITH_botan_PLUGIN) doesn't actually exist in qca - maybe it was an option in an older version?
- qca gives a warning message about the bad config option, but installs without problems - Botan is detected and used automatically.
- I've fixed the _optional_depends_ for Botan, and reformatted _ca_certificates_ for consistency.

qca - fix DEPENDS

---

plasma/plasma-workspace/DEPENDS
plasma/plasma-workspace/DETAILS

DEPENDS:
- does not actually require _ksystemstats_
- _does_ require _ktexteditor_ (build fails without it)
DETAILS:
- update UPDATED

plasma-workspace - fix depends

---

plasma/plasma-workspace/DEPENDS

Yet more dependencies for _plasma-workspace._ It won't build without them.
- networkmanager-qt is a hard dep, so I removed the _optional,_ which was commented out anyway (?)
**IMPORTANT:** there's a PR for a new module submitted - _kuserfeedback._ It needs to be approved before this will work. Check that out first.

plasma-workspace, update DEPENDS

---

frameworks/kuserfeedback/DEPENDS
frameworks/kuserfeedback/DETAILS

New module - now required by _plasma-workspace,_ build of 5.22 fails without it.
Module description from KDE:
KDE Framework for collecting user feedback for apps via telemetry and surveys

kuserfeerback, depends of plasma-workspace

---

crater/README

The creation of this file is mostly justified to keep the directory present even if there's no modules in it. And it doesn't hurt to add a little description to it :)

kde/crater: add a basic README
