graphics/gwenview/DEPENDS, utils/kate/DEPENDS
=> add missing kf5 dependencies

qt5-apps/stellarium/PRE_BUILD
No idea why this doesn't happen everywhere...
=> stellarium: fix build by adding missing includes

qt4-apps/scribus/DETAILS
=> scribus: fix broken DETAILS

utils/soprano/BUILD
it now installs /usr/lib/libsoprano.so.4 and some other relevant files...
=> soprano: cleanup the build

qt5-apps/mlt/BUILD, qt5-apps/mlt/DEPENDS
The module was broken with no pulseaudio installed.
=> pulseaudio is an optional dependency

applications/akonadi-search/DEPENDS
=> akonadi-search: add dep kdepimlibs

qt4-apps/lyx/BUILD, qt4-apps/lyx/DEPENDS, qt4-apps/lyx/DETAILS
It can be builded with qt5 or qt4.
=> lyx: version bumped to 2.2.0.

qt4-apps/qt4/PRE_BUILD
=> qt4: fix build with current moonbase

qt5-apps/qt5/DETAILS
=> qt5:Add download URL

frameworks/plasma-framework/DEPENDS
plasma-framework:Adding a depends.
=> plasma-framework:Adding a depends.

qt5-apps/qt5/BUILD, qt5-apps/qt5/patch.d/04-qtbase-Fix-qmake-build-with-glibc-2.28.patch, qt5-apps/qt5/patch.d/05-qtbase-Check-glibc-version-for-renameat2-statx-on-non-boots.patch, qt5-apps/qt5/patch.d/qtnetwork-5.11.1-libressl.patch
- cleanup qt5 module
- fix build with glibc 2.28
- fix build with libressl 2.7.4
=> Qt5 fix libressl & glibc

system/qt5/patch.d/patch-src_network_ssl_qsslcontext__openssl.cpp, system/qt5/patch.d/patch-src_network_ssl_qsslsocket__openssl11__symbols__p.h, system/qt5/patch.d/patch-src_network_ssl_qsslsocket__openssl__symbols.cpp, system/qt5/patch.d/patch-src_network_ssl_qsslsocket__openssl__symbols__p.h
thanks to the FreeBSD folks for these patches!
=> qt5: add libressl patches

profiles/kf5/DETAILS
=> kf5:fix a typo

frameworks/kwayland-frameworks/DETAILS
kwayland-frameworks:fix a typo
=> kwayland-frameworks:fix a typo

system/qt5/BUILD
=> qt5:fix a typo

applications/kdenlive/DEPENDS, applications/kdenlive/PRE_BUILD, frameworks/kdeclarative/patch.d/00-optional-qml-debugger.patch
fix minor issues I encountered with `lin kdenlive`
=> dependency issues

libs/libalkimia/DEPENDS
=> libalkimia: added missing DEPENDS

plasma/plasma-workspace/DEPENDS
added ksysguard and kwin to DEPENDS, fixed missing '$' in {PROBLEM_COLOR} notification.
=> plasma-workspace (2nd try): add missing dependencies, fix typo

apps/kmymoney/DEPENDS
added kdiagram and kdewebkit to DEPENDS
=> kmymoney: add missing DEPENDS

office/scribus/patch.d/scribus-1.5.5-qt-515.patch
patch file to work with qt 5.15
=> scribus - qt 5.15 fix

graphics/mlt/DETAILS
=> mlt:fix a typo

plasma/plasma-workspace/DEPENDS
=> plasma-workspace - update DEPENDS

system/qt5/BUILD, system/qt5/DEPENDS, system/qt5/DETAILS
=> qt5: require xcb support

frameworks/kwayland/DEPENDS, plasma/kwallet-pam/DEPENDS
`lin plasma` failed over here because of them.
=> kwayland,kwallet: add missing dependencies

applications/akonadi-contacts/DEPENDS
added dependency on libkleo - compile fails without it.
=> akonadi-contacts - add missing dependency

frameworks/ktextwidgets/DEPENDS, frameworks/ktextwidgets/DETAILS
DEPENDS updated to use python 3
=> fix python dependency

frameworks/kcontacts/DEPENDS, frameworks/kcontacts/DETAILS
update DEPENDS to use python 3
=> kcontacts -fix python dependency

system/qt5/BUILD, system/qt5/PRE_BUILD
- adjust path to `ls` for test
- use bundled version of assimp for quick3d
=> fix qt5 build

office/scribus/BUILD, office/scribus/DETAILS
=> scribus version bump

system/qt5/BUILD, system/qt5/DETAILS
This was broken for *4* years, but I noticed it only by accident because
mkvtoolnix broke because of it recently.
=> qt5: fix profile.d file

applications/kdeconnect-kde/DEPENDS
adding some missing dependencies for kdeconnect, also updating to python3
=> kdeconnect, updated dependencies

plasma/kwin/DEPENDS
fixed a dependency - needs _kwayland-server,_ not _kwayland_ (which is then installed by _kwayland-server_)
=> kwin update DEPENDS

frameworks/kdoctools/DEPENDS, frameworks/kfilemetadata/DEPENDS, frameworks/kwallet/DEPENDS, frameworks/kxmlgui/DEPENDS
I know we normally don't like single commits for multiple modules, but it's the same change to all four: updating to use python3
=> kdoctools, kfilemetadata, wallet, kxmlgui: python3 update

applications/kmailtransport/BUILD
=>  kmailtransport:fix a typo

applications/konsole/BUILD
=> konsole:fix a typo

plasma/plasma-workspace/DETAILS
plasma-workspace:The URL has changed
=> plasma-workspace:The URL has changed
